const GRE_DEFS = {
  'abnegation': 'self-denial or sacrifice',
  'accolade': 'praise or award',
  'acerbic': 'sharp and harsh words',
  'acquiesce': 'agree without protest',
  'admonish': 'warn or scold gently',
  'aggrandize': 'make seem greater',
  'alacrity': 'eager willingness',
  'ameliorate': 'make better',
  'anachronism': 'out of its time',
  'anathema': 'something deeply hated',
  'antipathy': 'strong dislike',
  'apocryphal': 'probably not true',
  'approbation': 'official approval or praise',
  'arcane': 'secret and mysterious',
  'arduous': 'very hard to do',
  'ascetic': 'lives simply, avoids pleasure',
  'assuage': 'calm or relieve',
  'audacious': 'boldly daring',
  'auspicious': 'good sign for success',
  'avarice': 'extreme greed',
  'bellicose': 'eager to fight',
  'blandishment': 'flattery to persuade',
  'bombastic': 'overly grand speech',
  'bucolic': 'peaceful countryside',
  'burgeon': 'grow rapidly',
  'cacophony': 'harsh loud noise',
  'calumny': 'false damaging claim',
  'capricious': 'unpredictably changeable',
  'castigate': 'harshly criticize',
  'caustic': 'burns or bites sharply',
  'censure': 'officially condemn',
  'chary': 'cautious and wary',
  'chicanery': 'sneaky trickery',
  'cogent': 'clear and convincing',
  'commensurate': 'equal in proportion',
  'compunction': 'guilt or regret',
  'concomitant': 'naturally accompanying',
  'contentious': 'causing disagreement',
  'contrite': 'deeply sorry',
  'contumacious': 'stubbornly disobedient',
  'conundrum': 'confusing problem',
  'copious': 'very plentiful',
  'cosset': 'pamper excessively',
  'credulous': 'too easily fooled',
  'cupidity': 'greedy desire',
  'dauntless': 'fearless and brave',
  'debacle': 'sudden total failure',
  'decorum': 'proper polite behavior',
  'deferential': 'respectfully submissive',
  'deleterious': 'causing harm',
  'demagogue': 'leader who stirs emotions',
  'denigrate': 'unfairly put down',
  'denouement': 'story\'s final resolution',
  'deprecate': 'express disapproval',
  'derisive': 'mocking and scornful',
  'desiccate': 'dry out completely',
  'desultory': 'random and unfocused',
  'diaphanous': 'light and see-through',
  'didactic': 'meant to teach',
  'diffident': 'shy and lacking confidence',
  'dilettante': 'amateur dabbler',
  'disabuse': 'correct a false belief',
  'discordant': 'clashing, not in harmony',
  'discomfit': 'make uneasy',
  'disparate': 'very different',
  'dissemble': 'hide true feelings',
  'dissonance': 'harsh disagreement',
  'dogmatic': 'rigid in beliefs',
  'ebullience': 'bubbly enthusiasm',
  'effrontery': 'shameless boldness',
  'egregious': 'outrageously bad',
  'elegy': 'sad poem of mourning',
  'emollient': 'softening or soothing',
  'encomium': 'high praise speech',
  'endemic': 'native to one area',
  'enervate': 'drain of energy',
  'ephemeral': 'lasts very briefly',
  'equanimity': 'calm under pressure',
  'equivocal': 'deliberately unclear',
  'erudite': 'very knowledgeable',
  'esoteric': 'known by very few',
  'eulogy': 'speech praising the dead',
  'evanescent': 'quickly fades away',
  'exacerbate': 'make worse',
  'excoriate': 'harshly criticize',
  'exculpate': 'clear of blame',
  'exigent': 'urgent and demanding',
  'exonerate': 'officially clear of guilt',
  'expedient': 'convenient and practical',
  'expiate': 'make up for wrongdoing',
  'expunge': 'erase completely',
  'extant': 'still existing',
  'extemporaneous': 'spoken without preparation',
  'extrapolate': 'extend beyond known data',
  'extraneous': 'not relevant',
  'exultant': 'joyfully triumphant',
  'facetious': 'joking at wrong time',
  'fallacious': 'based on false reasoning',
  'fastidious': 'very attentive to detail',
  'fatuous': 'silly and pointless',
  'fecund': 'very fertile or productive',
  'felicitous': 'pleasantly suitable',
  'fervent': 'intensely passionate',
  'flagrant': 'obviously and openly wrong',
  'fledgling': 'new and inexperienced',
  'forbearance': 'patient self-control',
  'forlorn': 'sad and abandoned',
  'fortuitous': 'happening by lucky chance',
  'fractious': 'easily irritated',
  'furtive': 'sneaky and secretive',
  'garrulous': 'talks too much',
  'grandiloquent': 'uses pompous language',
  'gratuitous': 'unnecessary or unwarranted',
  'gregarious': 'loves being social',
  'guile': 'clever deception',
  'halcyon': 'happy and peaceful',
  'harangue': 'long angry lecture',
  'hegemony': 'dominant group control',
  'heresy': 'against accepted belief',
  'hubris': 'excessive arrogance',
  'iconoclast': 'attacks cherished beliefs',
  'ignominious': 'deeply shameful',
  'impassive': 'shows no emotion',
  'imperturbable': 'unshakably calm',
  'implacable': 'cannot be calmed',
  'impugn': 'question someone\'s honesty',
  'inchoate': 'just beginning, incomplete',
  'incipient': 'just starting to appear',
  'incisive': 'sharp and clear-minded',
  'incontrovertible': 'impossible to dispute',
  'indolent': 'lazy by nature',
  'indomitable': 'impossible to defeat',
  'ineffable': 'too great to describe',
  'inimical': 'harmful and hostile',
  'inimitable': 'impossible to copy',
  'insipid': 'dull and flavorless',
  'intractable': 'hard to manage',
  'inveterate': 'deeply habit-driven',
  'irascible': 'quickly gets angry',
  'ire': 'intense anger',
  'laconic': 'uses very few words',
  'lassitude': 'physical or mental tiredness',
  'laud': 'publicly praise',
  'lethargic': 'sluggish and tired',
  'loquacious': 'talks a lot',
  'lucid': 'clear and easy to understand',
  'lugubrious': 'excessively mournful',
  'magnanimous': 'very generous and forgiving',
  'malediction': 'a spoken curse',
  'malevolent': 'wishes harm on others',
  'malign': 'say bad things about',
  'malleable': 'easily shaped or influenced',
  'mendacious': 'tends to lie',
  'mercurial': 'moody and unpredictable',
  'meticulous': 'extremely careful and precise',
  'misanthrope': 'hates people generally',
  'mitigate': 'reduce harm or severity',
  'moribund': 'near death or end',
  'munificent': 'extremely generous',
  'myriad': 'countless and varied',
  'nefarious': 'wicked and criminal',
  'neophyte': 'beginner or newcomer',
  'nihilism': 'life has no meaning',
  'nocturnal': 'active at night',
  'nonchalant': 'casually unconcerned',
  'obdurate': 'stubbornly refuses to change',
  'obfuscate': 'make deliberately confusing',
  'oblique': 'indirect and slanted',
  'obsequious': 'overly eager to please',
  'obstinate': 'refuses to change mind',
  'obtuse': 'slow to understand',
  'occlude': 'block or close off',
  'officious': 'bossy and interfering',
  'onerous': 'heavy burden or duty',
  'opaque': 'hard to see through',
  'opprobrium': 'public disgrace',
  'ostracize': 'exclude from group',
  'overwrought': 'extremely nervous or upset',
  'paean': 'song of joyful praise',
  'palliate': 'ease without curing',
  'palpable': 'clearly felt or noticed',
  'panacea': 'cure for everything',
  'pariah': 'socially rejected outcast',
  'parsimonious': 'extremely cheap',
  'paucity': 'very small amount',
  'pedantic': 'obsessed with small details',
  'pejorative': 'insulting and belittling',
  'penchant': 'strong natural liking',
  'penury': 'extreme poverty',
  'perfidious': 'treacherously dishonest',
  'perfunctory': 'done carelessly and quickly',
  'perilous': 'full of danger',
  'pernicious': 'slowly causes serious harm',
  'perspicacious': 'very insightful and sharp',
  'pertinacious': 'stubbornly persistent',
  'petulant': 'childishly sulky',
  'phlegmatic': 'calm and unemotional',
  'pithy': 'brief and meaningful',
  'placid': 'calm and undisturbed',
  'platitude': 'overused boring statement',
  'plausible': 'seems likely or believable',
  'plethora': 'way too much',
  'poignant': 'deeply emotional',
  'polemical': 'sparks strong controversy',
  'portentous': 'warning something bad ahead',
  'pragmatic': 'practical over ideal',
  'preclude': 'prevent from happening',
  'predilection': 'preference for something',
  'prevaricate': 'avoid truth cleverly',
  'probity': 'strong moral integrity',
  'proclivity': 'natural tendency toward',
  'prodigal': 'recklessly wasteful spender',
  'prodigious': 'impressively enormous',
  'profligate': 'wildly wasteful',
  'propitious': 'favorable for success',
  'prosaic': 'dull and ordinary',
  'protean': 'readily changes form',
  'prudent': 'wise and careful',
  'pugnacious': 'loves to fight',
  'punctilious': 'very precise about rules',
  'pusillanimous': 'timid and cowardly',
  'quandary': 'state of confusion',
  'querulous': 'constantly complaining',
  'quixotic': 'unrealistically idealistic',
  'rancorous': 'bitter long-held resentment',
  'rapacious': 'aggressively greedy',
  'recalcitrant': 'stubbornly uncooperative',
  'recondite': 'known by very few',
  'redolent': 'strongly suggestive of',
  'remonstrate': 'protest or object firmly',
  'replete': 'completely full',
  'reprehensible': 'deserves strong blame',
  'reproach': 'express disappointment in',
  'repudiate': 'reject completely',
  'rescind': 'officially cancel',
  'reticent': 'quiet and reserved',
  'reverent': 'shows deep respect',
  'rhetoric': 'persuasive language or speech',
  'rigorous': 'very thorough and strict',
  'ruminative': 'deeply thoughtful',
  'sagacious': 'wise and practical',
  'salient': 'most important point',
  'sanguine': 'optimistic and cheerful',
  'sardonic': 'mocking and cynical',
  'scintillating': 'brilliantly clever',
  'scion': 'descendant of wealthy family',
  'scrupulous': 'very honest and careful',
  'sedulous': 'hardworking and diligent',
  'sententious': 'overly moralizing',
  'serendipity': 'lucky accidental discovery',
  'servile': 'overly submissive',
  'skeptic': 'doubts accepted claims',
  'solicitous': 'very caring and concerned',
  'soporific': 'causes sleep or boredom',
  'specious': 'seems true but isn\'t',
  'spurious': 'false or fake',
  'squalid': 'dirty and neglected',
  'stolid': 'shows little emotion',
  'strident': 'loud and harsh',
  'stupefy': 'make unable to think',
  'subvert': 'secretly undermine',
  'sycophant': 'flatters for personal gain',
  'tacit': 'understood without being said',
  'tangential': 'only slightly related',
  'temerity': 'reckless boldness',
  'tenacious': 'never gives up',
  'timorous': 'easily frightened',
  'torpor': 'mental or physical sluggishness',
  'tortuous': 'full of twists',
  'tractable': 'easy to manage',
  'transient': 'lasts only briefly',
  'trenchant': 'sharp and forceful',
  'trite': 'overused and boring',
  'truculent': 'eager to argue',
  'turpitude': 'wicked immoral behavior',
  'ubiquitous': 'seems to be everywhere',
  'umbrage': 'feeling offended',
  'unctuous': 'falsely charming',
  'vacillate': 'keep changing your mind',
  'vagary': 'unpredictable change',
  'vapid': 'dull and empty',
  'vehement': 'intensely forceful',
  'venal': 'easily bribed',
  'venerate': 'deeply respect',
  'veracious': 'truthful and honest',
  'verbose': 'uses too many words',
  'vex': 'annoy or frustrate',
  'vicarious': 'experienced through others',
  'vindictive': 'seeking revenge',
  'virulent': 'extremely hostile or toxic',
  'viscous': 'thick and sticky',
  'vitiate': 'weaken or corrupt',
  'vituperate': 'scold harshly',
  'vociferous': 'loud and outspoken',
  'voluble': 'talks easily and much',
  'wary': 'cautious and alert',
  'wistful': 'longing and slightly sad',
  'zealous': 'fiercely passionate',
  'zeal': 'intense enthusiasm',
  'zenith': 'highest point',
  'acrimony': 'bitter hostility',
  'adulation': 'excessive admiration',
  'amiable': 'friendly and pleasant',
  'amorphous': 'has no clear shape',
  'analogous': 'similar in function',
  'anodyne': 'not offensive or stimulating',
  'antagonize': 'provoke hostility',
  'apathetic': 'shows no interest',
  'appease': 'satisfy by giving in',
  'ardor': 'strong enthusiasm or passion',
  'arid': 'very dry',
  'arrogant': 'thinks too highly of oneself',
  'astute': 'cleverly perceptive',
  'atrophy': 'weaken from disuse',
  'augment': 'make larger',
  'austere': 'plain and strict',
  'autocratic': 'rules with total power',
  'aversion': 'strong dislike',
  'banal': 'boring and common',
  'beguile': 'charm or deceive',
  'benign': 'gentle and harmless',
  'berate': 'scold angrily',
  'blithe': 'happily carefree',
  'brazen': 'shamelessly bold',
  'brevity': 'using few words',
  'candid': 'honest and direct',
  'capitulate': 'give in and surrender',
  'catharsis': 'emotional release',
  'chastise': 'punish or scold',
  'clamor': 'loud confused noise',
  'clairvoyant': 'can see the future',
  'clemency': 'merciful leniency',
  'coerce': 'force through pressure',
  'cognizant': 'fully aware of',
  'colossal': 'extremely huge',
  'complacent': 'smugly self-satisfied',
  'condescend': 'act superior to others',
  'confound': 'surprise and confuse',
  'conspicuous': 'very easy to notice',
  'consummate': 'perfect or complete',
  'contemptuous': 'shows strong disrespect',
  'covert': 'secret and hidden',
  'craven': 'shamefully cowardly',
  'cryptic': 'mysterious and unclear',
  'culpable': 'deserves blame',
  'cynical': 'distrusts people\'s motives',
  'decry': 'publicly denounce',
  'defunct': 'no longer existing',
  'demur': 'raise an objection',
  'deplore': 'strongly disapprove of',
  'depravity': 'moral corruption',
  'deride': 'mock with contempt',
  'dexterous': 'skilled with hands',
  'diffuse': 'spread out widely',
  'diligent': 'steady and careful worker',
  'discern': 'recognize and understand',
  'disdain': 'strong contempt',
  'disingenuous': 'not truly sincere',
  'dispel': 'drive away or scatter',
  'distort': 'misrepresent or twist',
  'docile': 'easily managed',
  'dormant': 'temporarily inactive',
  'dubious': 'feeling doubtful',
  'duplicitous': 'deceitfully two-faced',
  'earnest': 'genuinely serious',
  'eccentric': 'unconventional and quirky',
  'edify': 'improve morally or mentally',
  'egotistical': 'selfishly self-centered',
  'elicit': 'draw out a response',
  'eloquent': 'speaks beautifully',
  'embellish': 'add details to exaggerate',
  'emulate': 'try to copy',
  'encumber': 'burden and restrict',
  'enigmatic': 'mysterious and puzzling',
  'equitable': 'fair to everyone',
  'erratic': 'unpredictable and inconsistent',
  'evasive': 'avoids direct answers',
  'exalt': 'praise or elevate highly',
  'exemplary': 'worth copying as example',
  'exhaustive': 'very thorough',
  'exile': 'banish from homeland',
  'fabricate': 'invent or fake',
  'ferment': 'stir up trouble',
  'ferocious': 'fiercely violent',
  'fickle': 'changes mind often',
  'flippant': 'disrespectfully casual',
  'florid': 'overly fancy and elaborate',
  'foment': 'stir up rebellion',
  'formidable': 'inspiring fear or respect',
  'frugal': 'avoids waste, saves money',
  'futile': 'pointless, no result',
  'gallant': 'brave and chivalrous',
  'garish': 'too bright and showy',
  'glib': 'smooth talk, little thought',
  'gluttonous': 'greedy for food',
  'hackneyed': 'used so often it\'s stale',
  'haughty': 'arrogantly superior',
  'heinous': 'shockingly evil',
  'heretical': 'against accepted beliefs',
  'hostile': 'unfriendly and aggressive',
  'hypocritical': 'says one thing, does another',
  'idiosyncratic': 'peculiar to one person',
  'immutable': 'never changes',
  'impetuous': 'acts without thinking',
  'incessant': 'never stops',
  'incongruous': 'out of place',
  'incredulous': 'hard to believe',
  'indefatigable': 'never gets tired',
  'indignant': 'angry at unfairness',
  'indulgent': 'allows too much',
  'infamous': 'known for being bad',
  'infuriate': 'make extremely angry',
  'ingenuous': 'innocent and naive',
  'innocuous': 'harmless and inoffensive',
  'insolent': 'rude and disrespectful',
  'insular': 'narrow-minded and isolated',
  'invective': 'harsh verbal attack',
  'irreverent': 'disrespectful of tradition',
  'jocular': 'fond of joking',
  'judicious': 'shows good judgment',
  'juxtapose': 'place side by side',
  'keen': 'sharp and eager',
  'kinetic': 'relating to motion',
  'languid': 'slow and relaxed',
  'laudable': 'deserves praise',
  'lax': 'not strict enough',
  'levity': 'treating seriously things lightly',
  'licentious': 'morally unrestrained',
  'listless': 'lacking energy or interest',
  'livid': 'extremely angry',
  'lofty': 'impressively high or grand',
  'malicious': 'intends to harm',
  'manifold': 'many and varied',
  'melancholy': 'deep sadness',
  'miserly': 'refuses to spend money',
  'mollify': 'calm someone\'s anger',
  'mundane': 'boring and ordinary',
  'naive': 'lacks experience or judgment',
  'narcissistic': 'obsessed with oneself',
  'negate': 'cancel out',
  'noxious': 'harmful and poisonous',
  'nuanced': 'subtle and complex',
  'objective': 'unbiased and fair',
  'oblivious': 'completely unaware',
  'ominous': 'threatening sign',
  'opportunistic': 'takes advantage of situations',
  'ornate': 'very elaborate decoration',
  'ostentatious': 'shows off wealth loudly',
  'outspoken': 'speaks boldly and directly',
  'patronize': 'talk down to someone',
  'pensive': 'deep in thought',
  'percipient': 'very observant',
  'peremptory': 'demanding instant obedience',
  'persistent': 'keeps going despite obstacles',
  'pliant': 'bends easily',
  'pompous': 'thinks one is important',
  'ponderous': 'slow and heavy',
  'precarious': 'dangerously unstable',
  'presumptuous': 'overstepping one\'s bounds',
  'prolific': 'produces a lot',
  'provincial': 'narrow small-town minded',
  'prudish': 'easily shocked by sex',
  'quiescent': 'quiet and inactive',
  'rash': 'acts without thinking',
  'rebuke': 'sharply criticize',
  'reckless': 'careless of consequences',
  'rectify': 'put something right',
  'redress': 'fix a wrong',
  'refute': 'prove wrong',
  'relentless': 'never stops or slows',
  'reluctant': 'unwilling to do something',
  'resolute': 'firmly determined',
  'retort': 'sharp witty reply',
  'revile': 'criticize with contempt',
  'rhetorical': 'for effect, not answer',
  'ruthless': 'shows no mercy',
  'sanctimonious': 'acts morally superior',
  'satirical': 'mocks using humor',
  'savvy': 'street-smart knowledge',
  'scornful': 'expresses contempt',
  'shrewd': 'clever in practical ways',
  'sinister': 'seems evil or threatening',
  'skeptical': 'doubtful and questioning',
  'slander': 'false harmful spoken claim',
  'slovenly': 'untidy and careless',
  'solemn': 'serious and grave',
  'somber': 'dark and gloomy',
  'stagnant': 'not moving or growing',
  'steadfast': 'loyally determined',
  'stoic': 'endures pain without complaint',
  'subdue': 'bring under control',
  'submissive': 'yields to authority',
  'sullen': 'quietly resentful',
  'superfluous': 'more than needed',
  'suppress': 'forcibly hold back',
  'susceptible': 'easily affected or harmed',
  'sycophantic': 'fawning and flattering',
  'systematic': 'organized and methodical',
  'tactful': 'careful not to offend',
  'tenuous': 'very weak or thin',
};
