const SAT_DEFS = {
  'abate': 'to reduce or lessen',
  'aberration': 'deviation from normal',
  'abstain': 'to hold yourself back',
  'adversity': 'hardship or difficulty',
  'advocate': 'to support or argue for',
  'aesthetic': 'relating to beauty',
  'alleviate': 'to ease pain or burden',
  'ambiguous': 'having unclear meaning',
  'amiable': 'friendly and pleasant',
  'analogy': 'comparison of two things',
  'anarchy': 'no rules or government',
  'anecdote': 'short personal story',
  'antagonist': 'the main opponent',
  'apathy': 'lack of interest or feeling',
  'appease': 'to calm someone down',
  'arbitrary': 'random, no clear reason',
  'arcane': 'mysterious and obscure',
  'arduous': 'very difficult and tiring',
  'articulate': 'to express clearly',
  'ascertain': 'to find out for sure',
  'astute': 'clever and sharp-minded',
  'atrophy': 'to weaken from disuse',
  'audacious': 'bold and daring',
  'augment': 'to add to or increase',
  'austere': 'simple and plain, strict',
  'authentic': 'real and genuine',
  'avarice': 'greed for wealth',
  'aversion': 'strong dislike',
  'benevolent': 'kind and generous',
  'biased': 'unfairly favoring one side',
  'bolster': 'to strengthen or support',
  'brevity': 'shortness, especially in speech',
  'candid': 'honest and straightforward',
  'capacious': 'having lots of space',
  'capitulate': 'to give in or surrender',
  'capricious': 'impulsive and unpredictable',
  'caustic': 'sharply critical or sarcastic',
  'charlatan': 'a fake or fraud',
  'chronic': 'ongoing and long-lasting',
  'circumspect': 'careful and cautious',
  'clandestine': 'secret and hidden',
  'coerce': 'to force someone to act',
  'coherent': 'logical and clearly organized',
  'complacent': 'too satisfied, self-satisfied',
  'concede': 'to admit or give up',
  'concise': 'brief and to the point',
  'condone': 'to allow or overlook wrongdoing',
  'convoluted': 'overly complicated and confusing',
  'copious': 'large in quantity, abundant',
  'credulous': 'too easily fooled or tricked',
  'culpable': 'deserving blame or guilt',
  'cynical': 'distrustful of people\'s motives',
  'daunting': 'intimidating and overwhelming',
  'debilitate': 'to weaken severely',
  'decorum': 'proper and polite behavior',
  'defer': 'to put off or yield to',
  'deliberate': 'careful and intentional',
  'demagogue': 'leader who manipulates people',
  'denounce': 'to publicly condemn',
  'deplete': 'to use up a resource',
  'deride': 'to mock or ridicule',
  'despondent': 'feeling hopeless and sad',
  'diligent': 'hardworking and dedicated',
  'discern': 'to recognize or distinguish',
  'disdain': 'contempt or scorn',
  'disparate': 'very different from each other',
  'dissent': 'to disagree with majority',
  'dogmatic': 'stubbornly fixed in beliefs',
  'dubious': 'doubtful or suspicious',
  'eccentric': 'odd or unconventional',
  'eloquent': 'speaking or writing beautifully',
  'emulate': 'to imitate and match',
  'enigmatic': 'mysterious and puzzling',
  'ephemeral': 'lasting only briefly',
  'equivocal': 'vague and open to doubt',
  'erratic': 'unpredictable and inconsistent',
  'erudite': 'deeply knowledgeable and learned',
  'exacerbate': 'to make worse',
  'exemplary': 'outstanding, worthy of imitation',
  'exhaustive': 'thorough and complete',
  'exonerate': 'to clear of blame',
  'expedient': 'convenient but possibly wrong',
  'explicit': 'clear and direct',
  'extol': 'to praise highly',
  'exuberant': 'enthusiastic and full of energy',
  'fallacious': 'based on false reasoning',
  'fervent': 'very passionate or intense',
  'flagrant': 'obviously wrong, outrageous',
  'flippant': 'not serious when it matters',
  'flourish': 'to grow and thrive',
  'fluctuate': 'to rise and fall repeatedly',
  'formidable': 'impressively powerful or difficult',
  'frugal': 'careful with money, thrifty',
  'futile': 'pointless and useless',
  'grandiose': 'overly impressive, exaggerated',
  'gregarious': 'outgoing and sociable',
  'guile': 'clever and deceptive trickery',
  'hamper': 'to slow down or hinder',
  'haughty': 'arrogantly superior, snobbish',
  'hegemony': 'dominance over others',
  'heresy': 'belief against official doctrine',
  'hypocrite': 'someone who fakes values',
  'hypothetical': 'based on a possible situation',
  'illuminate': 'to clarify or light up',
  'immutable': 'unable to be changed',
  'impede': 'to obstruct or block',
  'implicit': 'implied, not directly stated',
  'impulsive': 'acting without thinking first',
  'inadvertent': 'accidental, not on purpose',
  'incite': 'to provoke or stir up',
  'indifferent': 'not caring either way',
  'indignant': 'angry about something unfair',
  'inept': 'unskilled and clumsy',
  'inevitable': 'certain to happen',
  'infer': 'to conclude from evidence',
  'ingenious': 'cleverly creative or inventive',
  'innate': 'natural, born with it',
  'insightful': 'showing deep understanding',
  'integrity': 'strong moral honesty',
  'intuitive': 'based on gut feeling',
  'irony': 'opposite of what\'s expected',
  'jeopardize': 'to put at risk',
  'juxtapose': 'to place side by side',
  'kindle': 'to spark or ignite',
  'languid': 'weak and lacking energy',
  'lethargic': 'sluggish and lacking energy',
  'lucid': 'clear and easy to understand',
  'magnanimous': 'generous and forgiving',
  'malevolent': 'having evil intentions',
  'malleable': 'easily shaped or influenced',
  'meticulous': 'extremely careful and precise',
  'mitigate': 'to lessen the severity',
  'mollify': 'to calm someone\'s anger',
  'monotonous': 'boring and repetitive',
  'nonchalant': 'casually calm and unconcerned',
  'notorious': 'famous for something bad',
  'nuance': 'subtle difference or distinction',
  'oblivious': 'completely unaware',
  'obscure': 'unclear or not well known',
  'obsolete': 'no longer useful or used',
  'obstinate': 'stubbornly refusing to change',
  'ominous': 'threatening and foreboding',
  'opaque': 'not transparent, hard to understand',
  'opportunist': 'one who exploits situations',
  'ostracize': 'to exclude from the group',
  'overwhelm': 'to overpower completely',
  'paradox': 'something contradicting itself',
  'partisan': 'strongly supporting one side',
  'passive': 'accepting without resistance',
  'patronize': 'to talk down to someone',
  'pedantic': 'overly focused on minor details',
  'persist': 'to keep going despite obstacles',
  'pervasive': 'spreading throughout everything',
  'plausible': 'seems reasonable and believable',
  'pragmatic': 'practical and realistic',
  'preclude': 'to prevent from happening',
  'pretentious': 'trying to seem important',
  'prevalent': 'widespread and common',
  'profound': 'deep and meaningful',
  'prolific': 'producing a large amount',
  'propaganda': 'biased info to persuade people',
  'prudent': 'wise and careful',
  'querulous': 'always complaining',
  'rancor': 'bitter, long-lasting hatred',
  'rationalize': 'to justify with excuses',
  'rebuke': 'to sharply criticize or scold',
  'rectify': 'to fix or correct',
  'refute': 'to prove wrong or false',
  'relentless': 'never stopping, persistent',
  'reluctant': 'unwilling, hesitant',
  'remorse': 'deep guilt and regret',
  'resilient': 'able to bounce back',
  'reticent': 'not willing to talk much',
  'rhetoric': 'persuasive language or speech',
  'rigorous': 'thorough and demanding',
  'robust': 'strong and healthy',
  'scrutinize': 'to examine very closely',
  'serendipity': 'happy accident or lucky find',
  'skeptical': 'doubtful and questioning',
  'solemn': 'serious and dignified',
  'stagnant': 'not moving or growing',
  'stoic': 'enduring pain without complaining',
  'subjective': 'based on personal opinion',
  'subtle': 'not obvious, hard to notice',
  'superficial': 'shallow, surface-level only',
  'suppress': 'to hold back or stop',
  'susceptible': 'easily affected or influenced',
  'sustain': 'to keep going, maintain',
  'tangible': 'real and touchable',
  'tenacious': 'refusing to give up',
  'tentative': 'uncertain and cautious',
  'thwart': 'to block or stop',
  'timid': 'shy and easily scared',
  'trivial': 'unimportant and minor',
  'turbulent': 'chaotic and unstable',
  'ubiquitous': 'found absolutely everywhere',
  'undermine': 'to weaken from within',
  'unprecedented': 'never happened before',
  'validate': 'to confirm or approve',
  'verbose': 'using too many words',
  'versatile': 'able to adapt to many things',
  'vigilant': 'watchful and alert',
  'vindicate': 'to clear of blame',
  'virtue': 'moral goodness or excellence',
  'volatile': 'unpredictable and explosive',
  'wary': 'cautious and watchful',
  'zealous': 'extremely enthusiastic',
  'abridge': 'to shorten a text',
  'abstemious': 'moderate in eating and drinking',
  'acrimony': 'bitter and angry resentment',
  'adamant': 'refusing to change one\'s mind',
  'admonish': 'to warn or scold gently',
  'adroit': 'skillful and clever',
  'affable': 'friendly and easy to talk to',
  'aggrandize': 'to make oneself seem greater',
  'aggrieve': 'to cause grief or injustice',
  'aloof': 'distant and unfriendly',
  'altruism': 'selfless concern for others',
  'ambivalent': 'having mixed feelings',
  'ameliorate': 'to make something better',
  'anachronism': 'something out of its time',
  'animus': 'strong hostility or hatred',
  'approbation': 'official approval or praise',
  'apt': 'fitting and appropriate',
  'ardent': 'very passionate and enthusiastic',
  'arrogant': 'overly proud and superior',
  'assiduous': 'hardworking and diligent',
  'atone': 'to make up for wrongdoing',
  'austerity': 'extreme simplicity, no extras',
  'autonomy': 'self-governing, independence',
  'banal': 'boring and unoriginal',
  'beguile': 'to charm and deceive',
  'belligerent': 'aggressive and looking for fights',
  'bemoan': 'to complain or express grief',
  'benign': 'gentle and harmless',
  'blatant': 'obvious and shameless',
  'boisterous': 'loud and energetic',
  'boon': 'a helpful benefit or gift',
  'bravado': 'fake boldness to impress',
  'camaraderie': 'friendly group loyalty',
  'candor': 'honesty and openness',
  'catalyst': 'something that causes change',
  'censure': 'to officially criticize',
  'circumvent': 'to find a way around',
  'clairvoyant': 'able to see the future',
  'clemency': 'mercy or leniency',
  'coalesce': 'to combine into one',
  'cogent': 'clear and convincing',
  'collaborate': 'to work together',
  'collude': 'to secretly plot together',
  'compel': 'to force someone to act',
  'competent': 'capable and qualified',
  'complacency': 'smugly satisfied, no drive',
  'conciliate': 'to make peace, reconcile',
  'condescend': 'to act superior to others',
  'confound': 'to confuse and bewilder',
  'conspicuous': 'easily noticed, standing out',
  'contempt': 'lack of respect, scorn',
  'contrite': 'very sorry and guilty',
  'corroborate': 'to confirm with evidence',
  'counterfeit': 'a fake copy of something',
  'craven': 'cowardly and spineless',
  'cynicism': 'distrust of people\'s goodness',
  'dearth': 'a shortage or lack',
  'decadent': 'self-indulgent and excessive',
  'deference': 'respectful submission to others',
  'deliberation': 'careful thinking before deciding',
  'delude': 'to mislead or fool oneself',
  'demure': 'modest and reserved',
  'depict': 'to show or describe',
  'desolate': 'empty, bleak, and lonely',
  'destitute': 'completely without money',
  'didactic': 'intended to teach a lesson',
  'diffident': 'shy and lacking confidence',
  'digress': 'to go off the main topic',
  'diligence': 'steady effort and hard work',
  'discord': 'lack of agreement, conflict',
  'discriminate': 'to treat groups differently',
  'disdainful': 'showing contempt or scorn',
  'disparage': 'to belittle or talk down',
  'dissemble': 'to hide one\'s true feelings',
  'distort': 'to twist out of shape',
  'diverge': 'to split or move apart',
  'diverse': 'varied and different',
  'docile': 'easily managed or obedient',
  'dominant': 'most powerful or influential',
  'dormant': 'inactive but not gone',
  'duplicity': 'double-dealing and deceit',
  'earnest': 'sincere and serious',
  'ebullient': 'cheerful and bubbling with energy',
  'egregious': 'shockingly bad or outrageous',
  'elusive': 'hard to find or pin down',
  'emaciated': 'extremely thin and weak',
  'embellish': 'to add details or exaggerate',
  'empathy': 'understanding another\'s feelings',
  'endemic': 'common to a specific area',
  'enthrall': 'to captivate completely',
  'enumerate': 'to list one by one',
  'equanimity': 'calm and composed mindset',
  'erroneous': 'mistaken and incorrect',
  'exasperate': 'to really annoy or frustrate',
  'excerpt': 'a short taken passage',
  'exhort': 'to strongly urge or encourage',
  'exorbitant': 'unreasonably expensive or excessive',
  'expedite': 'to speed up a process',
  'exploit': 'to take unfair advantage',
  'exquisite': 'extremely beautiful or delicate',
  'extravagant': 'spending way too much',
  'facade': 'a false outward appearance',
  'fastidious': 'very careful about details',
  'feasible': 'possible and practical',
  'fervor': 'intense passion or enthusiasm',
  'fickle': 'frequently changing opinions',
  'fleeting': 'passing very quickly',
  'florid': 'overly elaborate or flowery',
  'fluent': 'speaking smoothly and easily',
  'foreboding': 'a feeling of coming danger',
  'frank': 'direct and honest',
  'frantic': 'wildly anxious or panicked',
  'frivolous': 'not serious or sensible',
  'garrulous': 'talking too much',
  'gluttony': 'excessive eating or consumption',
  'gravity': 'seriousness of a situation',
  'grotesque': 'disturbingly ugly or bizarre',
  'hamstring': 'to prevent or cripple',
  'hapless': 'unlucky and unfortunate',
  'harass': 'to repeatedly bother someone',
  'hardship': 'severe difficulty or suffering',
  'havoc': 'widespread chaos or destruction',
  'harrowing': 'extremely distressing or painful',
  'heed': 'to pay attention to',
  'heinous': 'shockingly wicked or evil',
  'herald': 'to announce or signal',
  'hindrance': 'something that slows progress',
  'hostile': 'unfriendly and aggressive',
  'humility': 'being modest, not arrogant',
  'hyperbole': 'extreme exaggeration for effect',
  'idealize': 'to view as perfect',
  'idiosyncrasy': 'a unique personal quirk',
  'ignoble': 'shameful and dishonorable',
  'imminent': 'about to happen very soon',
  'impartial': 'fair and unbiased',
  'impertinent': 'rude and disrespectful',
  'impoverish': 'to make poor or deplete',
  'impudent': 'disrespectfully bold',
  'incisive': 'sharp and direct',
  'incongruous': 'out of place, doesn\'t fit',
  'indulge': 'to allow oneself a pleasure',
  'inert': 'unable to move or act',
  'infallible': 'never making mistakes',
  'inherent': 'built in, naturally part of',
  'inimical': 'harmful and hostile',
  'innovation': 'a new creative idea',
  'insolent': 'rude and disrespectful',
  'instigate': 'to start or provoke trouble',
  'intercede': 'to plead on another\'s behalf',
  'intrepid': 'fearless and adventurous',
  'irascible': 'easily angered and irritable',
  'irrefutable': 'impossible to deny or disprove',
  'justify': 'to give reasons to defend',
  'laborious': 'requiring much time and effort',
  'laconic': 'using very few words',
  'lament': 'to mourn or express grief',
  'latent': 'hidden, not yet active',
  'lenient': 'not strict, easy-going',
  'listless': 'lacking energy or enthusiasm',
  'lofty': 'very high or noble',
  'loquacious': 'talking a lot',
  'lucrative': 'producing a lot of money',
  'ludicrous': 'absurdly ridiculous',
  'malicious': 'intending to cause harm',
  'manifest': 'to show or become clear',
  'meager': 'very small in amount',
  'mediocre': 'just average, not great',
  'melancholy': 'deep sadness and gloom',
  'menacing': 'threatening or dangerous',
  'mercurial': 'constantly changing moods',
  'methodical': 'following a clear system',
  'militant': 'aggressive for a cause',
  'misconception': 'a wrong belief or idea',
  'morose': 'gloomy and bad-tempered',
  'mundane': 'ordinary and boring',
  'naive': 'too trusting and inexperienced',
  'negligent': 'careless and irresponsible',
  'nefarious': 'extremely evil or wicked',
  'neurotic': 'excessively anxious or worried',
  'nihilism': 'belief that nothing has meaning',
  'nominal': 'in name only, very small',
  'nostalgia': 'longing for the past',
  'noxious': 'harmful and toxic',
  'obdurate': 'stubbornly refusing to change',
  'objective': 'unbiased and fact-based',
  'oblique': 'indirect or not straightforward',
  'obsequious': 'overly eager to please',
  'obtuse': 'slow to understand things',
  'onerous': 'burdensome and difficult',
  'opulent': 'luxurious and wealthy',
  'orthodox': 'following traditional beliefs',
  'outspoken': 'speaking freely and boldly',
  'pacify': 'to calm or make peaceful',
  'palpable': 'easily felt or noticed',
  'paradigm': 'a standard example or model',
  'paragon': 'a perfect example',
  'pathetic': 'pitifully sad or weak',
  'patronage': 'support given to someone',
  'pensive': 'deep in thought, thoughtful',
  'peripheral': 'on the edge, not central',
  'perpetuate': 'to make something continue',
  'perturb': 'to upset or disturb',
  'philanthropic': 'caring and generous to others',
  'pithy': 'short but full of meaning',
  'poignant': 'deeply touching or moving',
  'pompous': 'self-important and arrogant',
  'portend': 'to be a warning sign',
  'pragmatism': 'focus on practical solutions',
  'precarious': 'unstable and risky',
  'precipitate': 'to cause something suddenly',
  'precocious': 'advanced beyond one\'s age',
  'predispose': 'to make likely beforehand',
  'presumptuous': 'overstepping what\'s appropriate',
  'prodigal': 'recklessly wasteful with money',
  'proficient': 'skilled and competent',
  'prohibit': 'to officially forbid something',
  'prologue': 'intro before the main story',
  'provocative': 'intended to stir strong reaction',
  'prudence': 'careful wisdom in decisions',
  'pugnacious': 'eager to argue or fight',
  'punitive': 'intended as punishment',
  'quandary': 'a state of uncertainty',
  'quarrelsome': 'always ready to argue',
  'quell': 'to suppress or put down',
  'radical': 'extreme and drastic change',
  'ramification': 'consequence of an action',
  'rancid': 'spoiled and foul-smelling',
  'rash': 'acting without thinking',
  'recalcitrant': 'stubbornly refusing to obey',
  'reclusive': 'preferring to be alone',
  'redemption': 'being saved or making amends',
  'refrain': 'to hold back from doing',
  'relegate': 'to send to a lower position',
  'remorseful': 'deeply sorry and guilty',
  'renounce': 'to officially give up',
  'reprehensible': 'deserving strong criticism',
  'resolute': 'firmly determined',
  'resonate': 'to have a deep impact',
  'retaliate': 'to fight back in return',
  'reverence': 'deep respect and awe',
  'rudimentary': 'basic and undeveloped',
  'ruthless': 'showing no mercy at all',
  'sacrosanct': 'too sacred to be questioned',
  'sagacious': 'wise and good at judging',
  'sanction': 'to officially allow or punish',
  'sarcasm': 'mocking words said ironically',
  'satire': 'humor that mocks to criticize',
  'shrewd': 'sharp-minded and clever',
  'simulate': 'to imitate or fake something',
  'slander': 'false spoken statements about someone',
  'solitary': 'alone, without others',
  'somber': 'dark and serious in mood',
  'speculate': 'to guess without full info',
  'spurious': 'fake and not genuine',
  'stifle': 'to suppress or hold back',
  'stipulate': 'to require as a condition',
  'stringent': 'strict and demanding',
  'stupefy': 'to astonish or stun',
  'subvert': 'to undermine and overthrow',
  'succinct': 'brief and clearly expressed',
  'superfluous': 'more than what\'s needed',
  'surpass': 'to go beyond or exceed',
  'sympathy': 'feeling sorry for others',
  'tacit': 'understood without being spoken',
  'temperance': 'moderation and self-control',
  'tenacity': 'persistent determination',
  'tepid': 'only slightly warm, lukewarm',
  'terse': 'brief and abrupt in speech',
  'timorous': 'easily frightened, timid',
  'toil': 'to work hard with effort',
  'transient': 'lasting only a short time',
  'trepidation': 'fear and anxiety',
  'truncate': 'to shorten by cutting off',
  'tumultuous': 'loud, chaotic, and disorderly',
  'tyranny': 'cruel and oppressive rule',
  'unassuming': 'modest and not boastful',
  'unequivocal': 'completely clear and certain',
  'unilateral': 'done by one side only',
  'usurp': 'to seize power illegally',
  'vacillate': 'to waver back and forth',
  'vague': 'unclear and not specific',
  'vanquish': 'to defeat completely',
  'veracious': 'truthful and accurate',
  'vex': 'to annoy or frustrate',
  'vilify': 'to speak badly about someone',
  'vindictive': 'seeking revenge',
  'vivid': 'bright and intensely clear',
  'voracious': 'extremely eager or hungry',
  'vulnerable': 'exposed to possible harm',
  'whimsical': 'playfully odd and fanciful',
  'wistful': 'longing for something past',
  'wrathful': 'extremely angry and furious',
  'xenophobia': 'fear of foreigners or outsiders',
  'yearning': 'deep longing or desire',
  'zeal': 'great enthusiasm and passion',
};
